language: cpp
compiler: gcc
dist: bionic
os: linux

matrix:
  include:
    - env: COMPILER=g++-7 BUILD=Release STANDARD=17
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - boost1.69

script:
        - cmake .
        - make
        - make test
