language: cpp
compiler: gcc
dist: bionic
os: linux
sudo: false

matrix:
  include:
    - env: COMPILER=g++-7 BUILD=Release STANDARD=17
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
install:
    - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
    - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
    - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic-rc main'
    - sudo apt update
    - sudo apt install cmake
 
before_script:
  - |
    function cond_call {
      if [[ "$(command -v $1)" ]]; then
        echo "Command: $1"
        echo "Verbose: $(command -v $1)"
        $@ --version
        echo "----------------"
      fi
    }

script:
  - lsb_release --all
  - apt-cache show cmake -a | grep Version
  - cond_call cmake
  - |
    LOCATIONS="$(whereis cmake)"
    for LOCATION in ${LOCATIONS:-}; do
      cond_call $LOCATION
    done
  - hash
  - echo $PATH

  - cmake .
  - make googletest
  - cmake .
  - make
  - make test
