language: cpp
compiler: gcc
dist: bionic
os: linux
sudo: false

matrix:
  include:
    - env: COMPILER=g++-7 BUILD=Release STANDARD=17
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - boost1.70

script:
        - cmake .
        - make googletest
        - cmake .
        - make
        - make test
